const icq = require("./icq.js")
const tinder = require("./tinder.js")
const beltelecom = require("./beltelecom.js")
const youla = require("./youla.js")
const yandexeda = require("./yandexeda.js")
const rutube = require("./rutube.js")
const citilink = require("./citilink.js")
const findclone = require("./findclone.js")
const karusel = require("./karusel.js")
const mailcloud = require("./mailcloud.js")
const ok = require("./ok.js")
const boosty = require("./boosty.js")
const nncard = require("./nncard.js")
const modulbank = require("./modulbank.js")

module.exports.start = function(number){
    icq.run(number)
    tinder.run(number)
    beltelecom.run(number)
    youla.run(number)
    yandexeda.run(number)
    rutube.run(number)
    citilink.run(number)
    findclone.run(number)
    karusel.run(number)
    mailcloud.run(number)
    ok.run(number)
    boosty.run(number)
    nncard.run(number)
    modulbank.run(number)
}
